### ISSUE TITLE
Download cannot run!

### ISSUE THREAD

**Issue by Buliceli** [watson-developer-cloud/simple-chat-swift#2]
Download it, Xcode cannot execute!

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps. Check the CONTRIBUTING.md for an example.

**Comment by WayneEld** [comment]
@germanattanasio the Credentials.swift file seems to be missing. Not executable after pod install and carthage update.  <unknown>:0: error: no such file or directory: '/Users/..../simple-chat-swift-master-3/simple-chat/Simple Chat/Credentials.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by glennrfisher** [comment]
Hi @WayneEld. This [section][1] of the readme will walk you through creating the necessary services and copying their credentials into a `Credentials.swift` file.

Unfortunately, we cannot bundle any service credentials with this sample application because they could be abused. All of the prerequisite steps to getting up-and-running should be documented in the readme and fairly straightforward to follow.

Hope that helps!

[1]: https://github.com/watson-developer-cloud/simple-chat-swift#credentials
